Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", disable: true
  config.vm.provision "shell", :path => "scripts/install_common.sh"


  config.vm.define :server1 do |server|
    server.vm.hostname = "server1"
    server.vm.network :private_network, ip: "172.10.10.2"
  end

  config.vm.define :server2 do |server|
    server.vm.hostname = "server2"
    server.vm.network :private_network, ip: "172.10.10.3"
  end
  
end
